settings:
  # this defines the free tags that can be given out to players
  # using the /ct free command.
  freetag:
    - "candysword"
    - "leafsword"
    - "lemonsword"
    - "mysterioussword"
    - "icesword"
    - "ominoussword"
    - "precioussword"
    - "pumpkinsword"
    - "rainbowsword"
    - "candypickaxe"
    - "leafpickaxe"
    - "lemonpickaxe"
    - "mysteriouspickaxe"
    - "oceanpickaxe"
    - "ominouspickaxe"
    - "preciouspickaxe"
    - "pumpkinpickaxe"
    - "rainbowpickaxe"
    - "candyaxe"
    - "leafaxe"
    - "lemonaxe"
    - "mysteriousaxe"
    - "oceanaxe"
    - "ominousaxe"
    - "preciousaxe"
    - "pumpkinaxe"
    - "rainbowaxe"
    - "candyshovel"
    - "leafshovel"
    - "lemonshovel"
    - "mysteriousshovel"
    - "oceanshovel"
    - "ominousshovel"
    - "preciousshovel"
    - "pumpkinshovel"
    - "rainbowshovel"
    - "candyhoe"
    - "leafhoe"
    - "lemonhoe"
    - "mysterioushoe"
    - "oceanhoe"
    - "ominoushoe"
    - "precioushoe"
    - "pumpkinhoe"
    - "rainbowhoe"

cosmetic:
  #This defines the lore of the cosmetic tag, dont remove the "Cosmetic Tag V2.0" line
  #Because we use that to define when a tag has been converted
  #I dont want to use the nbt tags
  taglore:
    - ""
    - "&cThis is an aesthetic skin!"
    - "&cApply the tag in an anvil."
    - ""
    - "&fCosmetic tags may be resold, gifted,"
    - "&for remain for personal use!"
    - "&6Cosmetic Tag V2.0"